# Generated by Django 3.1.1 on 2020-09-24 14:17

from django.db import migrations, models
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='body',
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blogpage',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
